package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"
	"fmt"

	"github.com/yihao2000/gqlgen-todos/graph/model"
)

// CreateBrand is the resolver for the createBrand field.
func (r *mutationResolver) CreateBrand(ctx context.Context, input model.NewBrand) (*model.Promo, error) {
	panic(fmt.Errorf("not implemented: CreateBrand - createBrand"))
}

// UpdateBrand is the resolver for the updateBrand field.
func (r *mutationResolver) UpdateBrand(ctx context.Context, input model.NewBrand) (*model.Promo, error) {
	panic(fmt.Errorf("not implemented: UpdateBrand - updateBrand"))
}

// Brands is the resolver for the brands field.
func (r *queryResolver) Brands(ctx context.Context) ([]*model.Brand, error) {
	panic(fmt.Errorf("not implemented: Brands - brands"))
}

// Brand is the resolver for the brand field.
func (r *queryResolver) Brand(ctx context.Context, id *string, name *string) (*model.Brand, error) {
	panic(fmt.Errorf("not implemented: Brand - brand"))
}
