package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"
	"fmt"

	"github.com/yihao2000/gqlgen-todos/graph/model"
)

// Promos is the resolver for the promos field.
func (r *queryResolver) Promos(ctx context.Context) ([]*model.Promo, error) {
	panic(fmt.Errorf("not implemented: Promos - promos"))
}
