package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/yihao2000/gqlgen-todos/config"
	"github.com/yihao2000/gqlgen-todos/graph/model"
)

// CreateShop is the resolver for the createShop field.
func (r *mutationResolver) CreateShop(ctx context.Context, input model.NewShop) (*model.Shop, error) {
	db := config.GetDB()

	// if ctx.Value("Role") == nil {
	// 	return nil, nil
	// }

	var shop model.Shop
	if err := db.Model(shop).Where("name LIKE ?", input.Name).Take(&shop).Error; err == nil {
		return nil, err
	} else {
		shop := model.Shop{
			ID:          uuid.New().String(),
			Name:        input.Name,
			Description: input.Description,
			Image:       input.Image,
			Aboutus:     input.Aboutus,
			Banner:      input.Banner,
			Banned:      false,
		}
		if err := db.Model(shop).Create(&shop).Error; err != nil {
			return nil, err
		}

		return &shop, nil
	}
}

// UpdateShop is the resolver for the updateShop field.
func (r *mutationResolver) UpdateShop(ctx context.Context, input model.NewShop) (*model.Shop, error) {
	panic(fmt.Errorf("not implemented: UpdateShop - updateShop"))
}

// Shops is the resolver for the shops field.
func (r *queryResolver) Shops(ctx context.Context) ([]*model.Shop, error) {
	panic(fmt.Errorf("not implemented: Shops - shops"))
}

// Shop is the resolver for the shop field.
func (r *queryResolver) Shop(ctx context.Context, id *string, name *string) (*model.Shop, error) {
	db := config.GetDB()

	shop := new(model.Shop)

	return shop, db.Where("id = ?", id).Limit(1).Find(&shop).Error
}

// ShopProducts is the resolver for the shopProducts field.
func (r *queryResolver) ShopProducts(ctx context.Context, shopID string, sortBy *string, limit *int, offset *int) ([]*model.Product, error) {
	db := config.GetDB()
	var models []*model.Product

	temp := db.Model(models).Where("shop_id = ?", shopID)

	if sortBy != nil {
		if *sortBy == "topsold" {
			temp = db.Model(models).
				Select("products.id, products.productgroup_id, products.brand_id, products.category_id, products.shop_id, products.name, products.description, products.price, products.image, products.quantity, products.valid_to, products.discount, SUM(transaction_details.quantity) as total_quantity").
				Joins("JOIN transaction_details ON products.id = transaction_details.product_id").
				Where("products.valid_to IS NULL AND shop_id = ?", shopID).
				Group("products.id").
				Order("total_quantity DESC")
		} else if *sortBy == "toprating" {
			temp = temp.Order("rating DESC")
		} else if *sortBy == "lowestprice" {
			return models, db.Where("shop_id = ? ", shopID).Order("price ASC").Find(&models).Error
		} else if *sortBy == "highestprice" {
			return models, db.Where("shop_id = ? ", shopID).Order("price DESC").Find(&models).Error
		} else if *sortBy == "mostreviews" {

		}
	}

	if limit != nil {
		temp = temp.Limit(*limit)
	}

	if offset != nil {
		temp = temp.Offset(*offset)
	}

	return models, temp.Find(&models).Error
}

// Products is the resolver for the products field.
func (r *shopResolver) Products(ctx context.Context, obj *model.Shop) ([]*model.Product, error) {
	db := config.GetDB()
	var models []*model.Product
	return models, db.Where("shop_id = ?", obj.ID).Find(&models).Error
}

// Shop returns ShopResolver implementation.
func (r *Resolver) Shop() ShopResolver { return &shopResolver{r} }

type shopResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *shopResolver) Banned(ctx context.Context, obj *model.Shop) (bool, error) {
	panic(fmt.Errorf("not implemented: Banned - banned"))
}
func (r *shopResolver) Banner(ctx context.Context, obj *model.Shop) (string, error) {
	panic(fmt.Errorf("not implemented: Banner - banner"))
}
