package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"
	"fmt"
	"time"

	"github.com/vektah/gqlparser/v2/gqlerror"
	"github.com/yihao2000/gqlgen-todos/config"
	"github.com/yihao2000/gqlgen-todos/graph/model"
	"github.com/yihao2000/gqlgen-todos/service"
)

// Login is the resolver for the login field.
func (r *authOpsResolver) Login(ctx context.Context, obj *model.AuthOps, email string, password string) (interface{}, error) {
	return service.UserLogin(ctx, email, password)
}

// Register is the resolver for the register field.
func (r *authOpsResolver) Register(ctx context.Context, obj *model.AuthOps, input model.NewUser) (interface{}, error) {
	return service.UserRegister(ctx, input)
}

// Auth is the resolver for the auth field.
func (r *mutationResolver) Auth(ctx context.Context) (*model.AuthOps, error) {
	return &model.AuthOps{}, nil
}

// UserUpdateInformation is the resolver for the userUpdateInformation field.
func (r *mutationResolver) UserUpdateInformation(ctx context.Context, currentPassword *string, newPassword *string, phone *string, balance *float64, banned *bool) (*model.User, error) {
	return service.UserUpdateInformation(ctx, currentPassword, newPassword, phone, balance, banned)
}

// UserInputVerificationCode is the resolver for the userInputVerificationCode field.
func (r *mutationResolver) UserInputVerificationCode(ctx context.Context, email string, verificationcode string) (*model.User, error) {
	db := config.GetDB()

	var user model.User
	if err := db.Model(user).Where("email LIKE ?", email).Take(&user).Error; err != nil {
		return nil, err
	}

	if user.VerificationCodeValidTime != nil {
		duration := time.Since(*user.VerificationCodeValidTime)

		if duration.Minutes() < -13 {
			return nil, &gqlerror.Error{
				Message: duration.String(),
			}
		}
	}

	user.VerificationCode = verificationcode
	validtime := time.Now().Add(time.Minute * 15)
	user.VerificationCodeValidTime = &validtime

	return &user, db.Save(user).Error
}

// ValidateUserVerificationCode is the resolver for the validateUserVerificationCode field.
func (r *mutationResolver) ValidateUserVerificationCode(ctx context.Context, email string, verificationcode string) (interface{}, error) {
	db := config.GetDB()

	var user model.User
	if err := db.Model(user).Where("email LIKE ?", email).Take(&user).Error; err != nil {
		return false, err
	}

	if user.VerificationCode == verificationcode {
		if time.Now().Before(*user.VerificationCodeValidTime) {
			token, err := service.JwtGenerate(ctx, user.ID)
			if err != nil {
				return nil, err
			}

			return map[string]interface{}{
				"token": token,
			}, nil
		} else {
			return false, &gqlerror.Error{
				Message: "Error, Verification Code Expired !",
			}
		}

	}

	return false, &gqlerror.Error{
		Message: "Error, Verification Code Ga Sama!",
	}
}

// UpdateUserInformation is the resolver for the updateUserInformation field.
func (r *mutationResolver) UpdateUserInformation(ctx context.Context, userID string, banned *bool) (*model.User, error) {
	db := config.GetDB()

	var user model.User
	if err := db.Model(user).Where("id LIKE ?", userID).Take(&user).Error; err != nil {
		return nil, err
	}

	if banned != nil {
		user.Banned = *banned
	}

	return &user, db.Save(user).Error
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id *string, email *string) (*model.User, error) {
	if id != nil {
		return service.UserGetByID(ctx, *id)

	} else {
		return service.UserGetByEmail(ctx, *email)
	}

	// return service.UserGetByEmail(ctx, *email)
}

// GetCurrentUser is the resolver for the getCurrentUser field.
func (r *queryResolver) GetCurrentUser(ctx context.Context) (*model.User, error) {
	return service.UserGetByToken(ctx)
}

// GetSubscribedUsers is the resolver for the getSubscribedUsers field.
func (r *queryResolver) GetSubscribedUsers(ctx context.Context) ([]*model.User, error) {
	db := config.GetDB()

	if ctx.Value("auth") == nil {
		return nil, &gqlerror.Error{
			Message: "Error, token gaada",
		}
	}

	userID := ctx.Value("auth").(*service.JwtCustomClaim).ID

	var user model.User
	if err := db.Model(user).Where("id LIKE ?", userID).Take(&user).Error; err != nil {
		return nil, err
	}

	if user.Role != "Admin" {
		return nil, &gqlerror.Error{
			Message: "You are not admin !",
		}
	}

	var users []*model.User

	temp := db.Where("users.role = 'User' AND users.news_letter_subscribe = ?", true)

	return users, temp.Find(&users).Error
}

// Protected is the resolver for the protected field.
func (r *queryResolver) Protected(ctx context.Context) (string, error) {
	return "Success" + fmt.Sprintf("%+v\n", ctx.Value("auth")), nil
}

// GetUserShop is the resolver for the getUserShop field.
func (r *queryResolver) GetUserShop(ctx context.Context) (*model.Shop, error) {
	db := config.GetDB()

	if ctx.Value("auth") == nil {
		return nil, &gqlerror.Error{
			Message: "Error, Invalid Token !",
		}
	}

	userID := ctx.Value("auth").(*service.JwtCustomClaim).ID

	var shop model.Shop
	if err := db.Model(shop).Where("user_id = ?", userID).Take(&shop).Error; err != nil {
		return nil, err
	}

	return &shop, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, limit *int, offset *int) ([]*model.User, error) {
	db := config.GetDB()

	if ctx.Value("auth") == nil {
		return nil, &gqlerror.Error{
			Message: "Error, token gaada",
		}
	}

	userID := ctx.Value("auth").(*service.JwtCustomClaim).ID

	var users []*model.User

	temp := db.Where("id != ?", userID)

	if limit != nil {
		temp = temp.Limit(*limit)
	}

	if offset != nil {
		temp = temp.Offset(*offset)
	}

	return users, temp.Find(&users).Error
}

// NoShopUsers is the resolver for the noShopUsers field.
func (r *queryResolver) NoShopUsers(ctx context.Context) ([]*model.User, error) {
	db := config.GetDB()

	var users []*model.User

	temp := db.Where("users.id NOT IN (SELECT user_id FROM shops)")

	// 	SELECT *
	// FROM users
	// WHERE users.id NOT IN (
	// SELECT user_id FROM shops
	// )

	return users, temp.Find(&users).Error
}

// AuthOps returns AuthOpsResolver implementation.
func (r *Resolver) AuthOps() AuthOpsResolver { return &authOpsResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type authOpsResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *queryResolver) GetSubscribedUser(ctx context.Context) ([]*model.User, error) {
	panic(fmt.Errorf("not implemented: GetSubscribedUser - getSubscribedUser"))
}

type userResolver struct{ *Resolver }
