// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthOps struct {
	Login    interface{} `json:"login"`
	Register interface{} `json:"register"`
}



type NewBrand struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type NewPromo struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Image       string `json:"image"`
}

type NewUser struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Phone    string `json:"phone"`
	Password string `json:"password"`
	Banned   bool   `json:"banned"`
	Role     string `json:"role"`
}
